export const copy = {
  bg: {
    nav: {
      services: "Услуги",
      howItWorks: "Как работи",
      results: "Резултати",
      whyUs: "Защо ние",
      faq: "Въпроси",
      cta: "Запази разговор",
    },
    hero: {
      eyebrow: "AI автоматизации за бизнеса",
      headlinePrefix: "Твоят бизнес отговаря за ",
      headlineHighlight: "60 секунди",
      headlineSuffix: ". Дори в 3 през нощта.",
      subheadline: "Reach Smart изгражда AI автоматизации за SaaS и e-commerce бизнеси: support агенти, които реално решават проблема, системи, които намират следващия ти клиент, и follow-up, който продава, докато спиш.",
      cta: "Запази безплатен разговор",
      microcopy: "30 минути. Без ангажимент. Излизаш с конкретен план какво да автоматизираш първо.",
    },
    problem: {
      eyebrow: "Проблемът",
      headline: "Не губиш клиенти, защото си слаб. Губиш ги, защото си бавен.",
      body1: "Клиентът пише в 23:40 и не може да си проследи поръчката. Отговор получава на сутринта. Дотогава вече е поискал refund.",
      body2: "Support екипът ти отговаря на един и същи въпрос за петдесети път този месец. Продавачите ти прекарват половината си ден в ровене за контакти, вместо в разговори с клиенти. Купувачът пазарува веднъж и изчезва, защото никой не го е потърсил след това.",
      body3: "Нито едно от тези неща не е драма само по себе си. Но събрани, те тихо изяждат маржа ти всеки месец.",
      punchline: "Проблемът не е екипът ти. Проблемът е, че върши работа, която не изисква човек.",
    },
    solution: {
      eyebrow: "Решението",
      headline: "Система, която работи, докато ти не можеш.",
      body: "Не продаваме „AI“, защото е модерно. Изграждаме конкретни автоматизации, които вършат конкретна работа: отговарят, намират, пишат, напомнят. Ти виждаш само резултата: решени казуси, пълен pipeline и клиенти, които се връщат.",
    },
    services: {
      eyebrow: "Какво правим",
      headline: "Автоматизирани системи за растеж",
      tabSaaS: "За SaaS бизнеси",
      tabEcom: "За E-commerce брандове",
      lineup: "Портфолиото ни расте. Ако процесът, който искаш да автоматизираш, не е тук, питай ни на разговора.",
      saas: [
        {
          title: "AI Chat Support Agent",
          hook: "Половината ти тикети са въпроси, на които вече си отговарял. Спри да им отговаряш втори път.",
          desc: "Чат агент, обучен върху твоята документация и данни, който отговаря на потребителите и им помага да решат проблема директно. Той не просто праща линкове към help center-а, а реално troubleshoot-ва. Когато срещне нещо, което не може да реши, прехвърля на екипа ти автоматично.",
          extra: "А ето най-ценната част: щом екипът ти реши случая, решението влиза в базата знания на агента. Следващия път, когато същият проблем се появи, той се справя сам. Всеки ескалиран тикет е последният път, в който го виждаш.",
          result: "Support екип, който се занимава само с наистина новите проблеми, а те стават все по-малко.",
          icon: "chat",
        },
        {
          title: "Lead Finder System",
          hook: "Продавачите ти трябва да продават. Не да ровят в LinkedIn по три часа на ден.",
          desc: "Системата открива бизнеси, които отговарят на идеалния ти клиентски профил, и намира точните хора вътре: тези, които реално взимат решението. Екипът ти получава готов списък за работа: компания, човек, контакт.",
          extra: "",
          result: "Sales екипът ти започва деня с разговори, а не с проучване.",
          icon: "target",
        },
        {
          title: "Lead Finder + Outreach System",
          hook: "От празен pipeline до отговори в inbox-а, без ти да напишеш и един имейл.",
          desc: "Всичко от Lead Finder системата, плюс автоматизиран персонализиран outreach. Системата намира правилните бизнеси и хора, после им праща имейли от твое име, писани спрямо конкретната компания, а не като copy-paste шаблон. Ти влизаш в разговора чак когато отсреща има реален интерес.",
          extra: "",
          result: "Квалифицирани разговори, които идват при теб, вместо ти да ги гониш.",
          icon: "outreach",
        },
      ],
      ecom: [
        {
          title: "AI Chat Support Agent",
          hook: "„Къде ми е поръчката?“ е отговорено в 2 през нощта, без теб.",
          desc: "Чат агент, който отговаря на въпросите на посетителите, проследява поръчки, препоръчва продукти и поема цялостната поддръжка, а когато не може да реши нещо, прехвърля на екипа ти. Помни решените случаи и става по-добър с всеки изминал месец.",
          extra: "И още нещо, което директно прави пари: хваща данните на посетителя и му пише, когато продуктът, който гледа, се върне в наличност или излезе нов. „Няма наличност“ спира да е изгубена продажба и става отложена.",
          result: "Обслужени клиенти денонощно и продажби, които иначе просто щяха да изтекат.",
          icon: "chat",
        },
        {
          title: "AI UGC Content Generator",
          hook: "Нов продукт в понеделник. Готови UGC видеа в понеделник.",
          desc: "Генерира UGC-стил видео съдържание (talking-to-camera демота, ревюта) директно от продуктовите ти снимки и листинги. Готово за постване в социалните мрежи или за рекламен криейтив.",
          extra: "Без да търсиш криейтъри за всеки нов продукт. Без да чакаш две седмици за доставка на контент. Без бюджетът за криейтиви да решава колко варианта можеш да тестваш, а точно обемът на тестването е това, което сваля цената на резултата в рекламите.",
          result: "Постоянен поток от свежи криейтиви на скоростта, с която пускаш продукти.",
          icon: "video",
        },
        {
          title: "AI Post-Purchase Flow System",
          hook: "Продажбата не свършва с „Поръчката е приета“. Там започва следващата.",
          desc: "Автоматично проследява клиента след покупка: ъпдейти за поръчката, персонализирани upsell и cross-sell оферти, заявка за ревю. Всяко нещо е в правилния момент от пътя на клиента, а не като спам на третия ден.",
          extra: "",
          result: "Еднократни купувачи, които стават редовни, и ревюта, които се трупат сами, без нито един ръчен follow-up.",
          icon: "refresh",
        },
      ],
    },
    howItWorks: {
      eyebrow: "Процесът",
      headline: "От разговор до работеща система, без ти да пишеш ред код.",
      steps: [
        {
          num: "01",
          title: "Разговор (безплатно)",
          desc: "30 минути. Разказваш ни как работи бизнесът ти. Ние ти казваме честно кое си струва да се автоматизира и кое не.",
        },
        {
          num: "02",
          title: "Изграждане",
          desc: "Строим системата, обучаваме я върху твоя бизнес и я тестваме, докато звучи и работи както трябва.",
        },
        {
          num: "03",
          title: "Пускане и настройка",
          desc: "Системата тръгва. Първите седмици следим всичко и я донастройваме по реални разговори и реални клиенти.",
        },
        {
          num: "04",
          title: "Ти гледаш числата",
          desc: "Хванати обаждания, отговорени лийдове, записани часове. Ако не виждаш разликата в календара си, значи не сме си свършили работата.",
        },
      ],
    },
    proof: {
      eyebrow: "Резултатите",
      headline: "Без приказки. Само резултати.",
      stats: [
        {
          val: "73%",
          label: "от запитванията за поддръжка се решават без човешка намеса",
          desc: "SaaS & E-commerce поддръжка",
        },
        {
          val: "120+",
          label: "квалифицирани лийдове, доставени на sales екипа за 30 дни",
          desc: "Lead Outreach автоматизация",
        },
        {
          val: "Секунди",
          label: "време за реакция, намалено от 4.5 часа средно за индустрията",
          desc: "Скорост на отговор",
        },
        {
          val: "60+",
          label: "UGC видео криейтиви месечно на цената на 3 от реален криейтър",
          desc: "Генериране на съдържание",
        },
      ],
      quote: "„Автоматизацията на чата съкрати времето ни за реакция от часове до секунди. Повечето рутинни въпроси се решават без намеса, а екипът ни се фокусира върху затварянето на сделки.“ (Георги Димитров, Основател на e-commerce бранд)",
    },
    whyUs: {
      eyebrow: "Защо Reach Smart",
      headline: "Трезви хора в хайп индустрия.",
      body1: "Всички продават AI. Малко от тях са пускали реклами, гонили лийдове и виждали какво реално се случва, когато системата не сработи.",
      body2: "Ние идваме от performance маркетинга: с години Meta реклами и генерирани клиенти за реални бизнеси. Знаем колко струва един лийд, защото сме плащали за него. Затова строим автоматизации, които пазят точно тази инвестиция.",
      body3: "И още нещо: ще ти кажем, ако нещо не ти трябва. Автоматизация, която не връща пари, е просто скъпа играчка, а ние не продаваме играчки.",
    },
    faq: {
      eyebrow: "FAQ",
      headline: "Въпроси, на които отговаряме веднага",
      items: [
        {
          q: "Клиентите ще усетят ли, че говорят с AI?",
          a: "Някои да, и това е окей. Важното е друго: клиентът получава отговор веднага, вместо да чака с часове. Тестовете ни показват, че хората предпочитат бърз отговор от AI пред бавен от човек. А за сложните случаи системата винаги прехвърля към теб.",
        },
        {
          q: "Колко време отнема изграждането?",
          a: "Зависи от системата, но повечето автоматизации са готови и активни до 3 седмици от първия разговор.",
        },
        {
          q: "Работи ли на български?",
          a: "Да. Системите ни говорят и пишат на естествен български, което е едно от нещата, които тестваме най-внимателно преди пускане.",
        },
        {
          q: "Колко струва?",
          a: "Зависи какво изграждаме, затова първият разговор е безплатен. Излизаш с ясна цена и ясен обхват, преди да си платил лев. Едно е сигурно: пропуснатите обаждания и лийдове вече ти струват повече.",
        },
        {
          q: "Ще ми трябва ли техническо познание?",
          a: "Не. Ние строим, настройваме и поддържаме всичко. Ти получаваш резултата и подробен отчет какво е свършено.",
        },
        {
          q: "Какво става, ако системата сгреши?",
          a: "Първите седмици следим всеки разговор и донастройваме. След това получаваш резюмета и винаги имаш човешки контрол върху важните случаи.",
        },
      ],
    },
    ctaSection: {
      headline: "Колко запитвания останаха без отговор тази седмица?",
      body: "Всеки ден без система е ден, в който екипът ти върши работа на робот, а клиенти изтичат при по-бързия. Запази 30 минути, в които ще ти покажем точно кой процес ти струва най-много и откъде да започнеш.",
      btn: "Запази безплатен разговор",
      microcopy: "Без ангажимент. Без техническо говорене. Само конкретен план.",
    },
    modal: {
      headline: "Запази безплатен разговор",
      subheadline: "Остави данните си и ние ще се свържем с теб до 24 часа.",
      nameLabel: "Твоето име",
      emailLabel: "Имейл адрес",
      companyLabel: "Име на фирмата",
      messageLabel: "Какво искаш да автоматизираш първо?",
      placeholderName: "Иван Иванов",
      placeholderEmail: "ivan@company.com",
      placeholderCompany: "Фирма ООД",
      placeholderMessage: "Искам да автоматизирам поддръжката на клиенти...",
      submit: "Изпрати запитване",
      successTitle: "Благодарим ти!",
      successDesc: "Запитването ти беше изпратено успешно. Ще се свържем с теб съвсем скоро.",
      error: "Нещо се обърка. Опитай отново или се свържи директно с нас.",
      loading: "Изпраща се...",
    },
    footer: {
      tagline: "Reach Smart: AI автоматизации за SaaS и e-commerce, които връщат времето на екипа ти.",
      copyright: "© 2026 Reach Smart. Всички права запазени.",
    },
  },
  en: {
    nav: {
      services: "Services",
      howItWorks: "How It Works",
      results: "Results",
      whyUs: "Why Us",
      faq: "FAQ",
      cta: "Book Call",
    },
    hero: {
      eyebrow: "AI Automations for Business",
      headlinePrefix: "Your business answers in ",
      headlineHighlight: "60 seconds",
      headlineSuffix: ". Even at 3 a.m.",
      subheadline: "Reach Smart builds AI automations for SaaS and e-commerce companies: support agents that actually solve the problem, systems that find your next customer, and follow-ups that sell while you sleep.",
      cta: "Book a Free Call",
      microcopy: "30 minutes. No strings attached. You'll walk away with a clear plan for what to automate first.",
    },
    problem: {
      eyebrow: "The Problem",
      headline: "You're not losing customers because you're bad. You're losing them because you're slow.",
      body1: "A customer messages at 11:40 p.m. and they can't track their order. They get an answer the next morning. By then, they've already filed for a refund.",
      body2: "Your support team answers the same question for the fiftieth time this month. Your salespeople spend half their day digging for contacts instead of talking to customers. A buyer purchases once and disappears, because nobody ever followed up.",
      body3: "None of these is a crisis on its own. Together, they quietly eat your margin every single month.",
      punchline: "The problem isn't your team. The problem is they're doing work that doesn't need a human.",
    },
    solution: {
      eyebrow: "The Solution",
      headline: "A system that works when you can't.",
      body: "We don't sell “AI” because it's trendy. We build specific automations that do specific jobs: answer, find, write, follow up. All you see is the result: resolved tickets, a full pipeline, and customers who come back.",
    },
    services: {
      eyebrow: "What We Do",
      headline: "Automated Systems Built for Growth",
      tabSaaS: "For SaaS Companies",
      tabEcom: "For E-commerce Brands",
      lineup: "Our lineup keeps growing. If the process you want to automate isn't listed here, bring it up on the call.",
      saas: [
        {
          title: "AI Chat Support Agent",
          hook: "Half your tickets are questions you've already answered. Stop answering them twice.",
          desc: "A chat agent trained on your documentation and business data that answers users and helps them troubleshoot directly. It doesn't just link to your help center, it actually solves the issue. When it hits something it can't resolve, it escalates to your team automatically.",
          extra: "Here's the part that compounds: once your team resolves the issue, the solution goes straight into the agent's knowledge base. Next time the same problem shows up, it handles it alone. Every escalated ticket is the last time you'll ever see it.",
          result: "A support team that only touches genuinely new problems, and there are fewer of them every month.",
          icon: "chat",
        },
        {
          title: "Lead Finder System",
          hook: "Your salespeople should be selling. Not spending three hours a day on LinkedIn.",
          desc: "The system finds companies that match your ideal customer profile and pinpoints the actual decision-makers inside them: the people who sign, not just anyone with a title. Your team gets a ready-to-work list: company, contact, details.",
          extra: "",
          result: "Your sales team starts the day with conversations, not research.",
          icon: "target",
        },
        {
          title: "Lead Finder + Outreach System",
          hook: "From empty pipeline to replies in your inbox, all without writing a single email.",
          desc: "Everything in the Lead Finder system, plus automated, personalized outreach. The system finds the right companies and the right people, then sends tailored emails on your behalf, written for that specific company, not a copy-paste blast. You step in only when there's genuine interest on the other end.",
          extra: "",
          result: "Qualified conversations that come to you, instead of you chasing them.",
          icon: "outreach",
        },
      ],
      ecom: [
        {
          title: "AI Chat Support Agent",
          hook: "“Where's my order?” is answered at 2 a.m., without you.",
          desc: "A chat agent that answers visitor questions, tracks orders, recommends products, and handles day-to-day customer support, escalating to your team when it can't resolve something. It remembers past resolutions and gets sharper every month.",
          extra: "And here's the part that directly makes money: it captures visitor details and reaches out when the product they wanted is back in stock or newly available. “Out of stock” stops being a lost sale and becomes a delayed one.",
          result: "Customers taken care of around the clock, and sales that would otherwise have simply walked away.",
          icon: "chat",
        },
        {
          title: "AI UGC Content Generator",
          hook: "New product on Monday. Ready-to-post UGC on Monday.",
          desc: "Generates UGC-style video content (talking-to-camera demos, testimonials) straight from your product photos and listings. Ready for social or ad creative the same day.",
          extra: "No hunting for creators every product launch. No two-week turnaround. No creative budget deciding how many variations you can test, and testing volume is exactly what drives your cost per result down.",
          result: "A steady stream of fresh creative, at the speed you ship products.",
          icon: "video",
        },
        {
          title: "AI Post-Purchase Flow System",
          hook: "The sale doesn't end at “Order confirmed.” That's where the next one starts.",
          desc: "Automatically follows up after every purchase: order updates, personalized upsell and cross-sell offers, and review requests, with each one timed to the right moment in the customer journey, not blasted out on day three.",
          extra: "",
          result: "One-time buyers who become repeat customers, and social proof that stacks up on its own, without a single manual follow-up.",
          icon: "refresh",
        },
      ],
    },
    howItWorks: {
      eyebrow: "Process",
      headline: "From a conversation to a working system, without you writing a line of code.",
      steps: [
        {
          num: "01",
          title: "The Call (free)",
          desc: "30 minutes. You tell us how your business runs. We tell you, honestly, what's worth automating and what isn't.",
        },
        {
          num: "02",
          title: "The Build",
          desc: "We build the system, train it on your business, and test it until it sounds and performs the way it should.",
        },
        {
          num: "03",
          title: "Launch and Tuning",
          desc: "The system goes live. For the first few weeks we monitor everything and fine-tune it against real conversations and real customers.",
        },
        {
          num: "04",
          title: "You Watch the Numbers",
          desc: "Tickets resolved, leads delivered, repeat orders. If you can't see the difference in your dashboard, we haven't done our job.",
        },
      ],
    },
    proof: {
      eyebrow: "Results",
      headline: "No pitch. Just numbers.",
      stats: [
        {
          val: "73%",
          label: "of support inquiries resolved with zero human involvement",
          desc: "SaaS & E-commerce support",
        },
        {
          val: "120+",
          label: "qualified leads delivered to the sales team in 30 days",
          desc: "Lead outreach automation",
        },
        {
          val: "Seconds",
          label: "response time, down from average 4.5 hours",
          desc: "Speed to lead",
        },
        {
          val: "60+",
          label: "UGC video creatives per month for the cost of 3 from a creator",
          desc: "Content generation",
        },
      ],
      quote: "“Implementing the chat automation reduced our response times from hours to seconds. It handles all common questions, letting our team focus on closing sales.” (Sarah Jenkins, Founder of Mucci Strength)",
    },
    whyUs: {
      eyebrow: "Why Reach Smart",
      headline: "Level-headed people in a hype-driven industry.",
      body1: "Everyone's selling AI right now. Very few of them have actually run ads, chased leads, and seen firsthand what happens when the system breaks.",
      body2: "We come from performance marketing: years of running Meta ads and generating customers for real businesses. We know what a lead costs, because we've paid for them. That's why we build automations that protect exactly that investment.",
      body3: "One more thing: we'll tell you when something isn't worth it. An automation that doesn't pay for itself is just an expensive toy, and we don't sell toys.",
    },
    faq: {
      eyebrow: "FAQ",
      headline: "Questions we answer right away",
      items: [
        {
          q: "Will customers know they're talking to AI?",
          a: "Some will, and that's fine. What matters is this: they get an answer instantly instead of waiting hours. In our testing, people consistently prefer a fast answer from AI over a slow one from a human. And for complex cases, the system always hands off to your team.",
        },
        {
          q: "How long does it take to build?",
          a: "Depends on the system, but most automations are live and active within 3 weeks of the first call.",
        },
        {
          q: "Will it work with our existing tools?",
          a: "That's the whole point. We build around your stack (your help desk, your store, your CRM) and not the other way around. We'll map it out together on the call.",
        },
        {
          q: "How much does it cost?",
          a: "Depends on what we're building, which is exactly why the first call is free. You'll leave with a clear price and a clear scope before you've spent a dollar. One thing's certain: the tickets and leads slipping through right now are already costing you more.",
        },
        {
          q: "Do we need technical people on our side?",
          a: "No. We build, configure, and maintain everything. You get the results and a report of what's been done.",
        },
        {
          q: "What happens when the system gets something wrong?",
          a: "For the first few weeks we review every conversation and fine-tune. After that, you get summaries, and you always keep human control over the cases that matter.",
        },
      ],
    },
    ctaSection: {
      headline: "How many inquiries went unanswered this week?",
      body: "Every day without a system is a day your team does robot work while customers leak to whoever answers faster. Book 30 minutes and we'll show you exactly which process is costing you the most, and where to start.",
      btn: "Book a Free Call",
      microcopy: "No commitment. No tech jargon. Just a concrete plan.",
    },
    modal: {
      headline: "Book a Free Call",
      subheadline: "Leave your details and we'll get back to you within 24 hours.",
      nameLabel: "Your Name",
      emailLabel: "Email Address",
      companyLabel: "Company Name",
      messageLabel: "What do you want to automate first?",
      placeholderName: "John Doe",
      placeholderEmail: "john@company.com",
      placeholderCompany: "Company Inc.",
      placeholderMessage: "I want to automate customer support...",
      submit: "Submit Request",
      successTitle: "Thank You!",
      successDesc: "Your request has been submitted successfully. We'll get back to you shortly.",
      error: "Something went wrong. Please try again or contact us directly.",
      loading: "Submitting...",
    },
    footer: {
      tagline: "Reach Smart: AI automations for SaaS and e-commerce that give your team its time back.",
      copyright: "© 2026 Reach Smart. All rights reserved.",
    },
  },
};
